### ISSUE TITLE
Assert hit in ttl_check_interval.rs

### ISSUE THREAD

**Issue by glademiller** [blackbeam/mysql_async#101] opened 2020-03-09 20:22 UTC
https://github.com/blackbeam/mysql_async/blob/master/src/conn/pool/ttl_check_inerval.rs#L70

right: `0`', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/mysql_async-0.22.1/src/conn/pool/ttl_check_inerval.rs:70:13

left: `160`

**Comment by blackbeam** [comment] 2020-03-10 04:22
@jonhoo, looks like this assert is the part of #65. Do you have any thoughts?

**Comment by jonhoo** [comment] 2020-03-10 13:13
Hmm.. This suggests that there are available connections in the pool, and yet for some reason there are threads waiting for connections. That doesn't seem right at all.

@glademiller Under what circumstances did this error occur? Is it reproducible? Could you try to come up with a simple test case where the error presents itself?

**Comment by glademiller** [comment] 2020-03-10 16:07
Any thoughts on what might be the cause. I have only seen this on an environment where the most I might be able to do is add some debug logs. My staging environment with a lot less going on hasn't hit the problem at all. In case it is important I have a pool that I clone between an actix-web service and background processing queue. If there is something I can put in the logs that would be helpful for debug please let me know.

**Comment by glademiller** [comment] 2020-03-10 16:09
Oh another bit of context this only started occurring after I upgraded to 0.22 and setting con_ttl and the inactive connection ttl and the ttl_check_interval.

**Comment by jonhoo** [comment] 2020-03-10 17:01
@glademiller Yeah, it makes sense you only see it in 0.22, since the assertion came with the rewrite of the pool logic in #92. I spent some time tracing through the logic of the code, and I _think_ I know what's going on. The issue is specifically in this code:
https://github.com/blackbeam/mysql_async/blob/f49716a50c6b7156b4a2ddaa349e0614101b9511/src/conn/pool/recycler.rs#L76-L79

We push to `available` and wake a thread that will then pick it up, but it won't pick it up _yet_. So if there are many futures waiting for a connection, and one becomes free, there will be a short period of time during which there is a connection in `available` *and* there are futures in `waiting`. I think the assertion is simply wrong and should be removed. We _could_ keep a count of "notified" and try to assert using that, but it's not worth the effort.

**Comment by blackbeam** [comment] 2020-03-11 08:16
Assert removed in cd214f1. @glademiller, is it possible to run this revision in your environment (as a git dependency)?

**Comment by blackbeam** [comment] 2020-03-15 17:12
I've modeled `Pool`, `Recycler` and `TtlCheckInterval` behavior in TLA+ and only found [minor issue] with `exchange.exist` counter, so I'm closing this for now.

There is no 100% guarantee that my model matches the implementation, so feel free to reopen if needed.

[minor issue]: https://github.com/blackbeam/mysql_async/commit/004f45e56dc563c225c3fadf153d2efcc50347e8

**Closed** 2020-03-15 20:18 UTC
